### ISSUE TITLE
Make it easy to write custom UdashRESTFrameworks

### ISSUE THREAD

**Issue by leonardehrenfried** [UdashFramework/udash-core#124]
Right now it's pretty difficult to use a different REST encoder other than the supplied one.

I took a stab at it here: https://github.com/leonardehrenfried/udash-circe/tree/master/src/main/scala/io/leonard/udash

However, it meant i had to copy the type `UsesREST` because the supplied one has a hardcoded dependency on the default rest framework.

```scala
abstract class UsesREST[ServerRPCType : DefaultRESTFramework.AsRealRPC : RPCMetadata : DefaultRESTFramework.ValidREST]
```
I would volunteer to author a PR getting rid of this but I think I need a little bit of guidance on how to do it best.

Thanks for your good work!

**Comment by Starzu** [comment]
Hi @leonardehrenfried.

First of all you should upgrade Udash to `0.6.0-M6` version. The implementation of the REST client has changed a little since `0.5.0`.  Take a look at #107. 

`UsesREST` doesn't depend on `DefaultRESTFramework` anymore, so there is no need to copy it. Also `CirceRESTFramework` doesn't need to extend `DefaultUdashSerialization`. 

As you can see in #107, now it's possible to expose REST interfaces as HTTP endpoint. It would be great, if you could create `CirceExposesREST` extending `ExposesREST`. You can modify `DefaultExposesREST` as you did with the `DefaultServerREST`.

If you have any more questions I'll be happy to answer.

**Comment by leonardehrenfried** [comment]
Thanks for the tips, @Starzu.

Upgrading to 0.6.0-M6 has indeed allowed me to get rid of a custom `UsesREST`, however the  `CirceServerRESTS` (https://github.com/leonardehrenfried/udash-circe/blob/master/src/main/scala/io/leonard/udash/CirceServerREST.scala#L9) is necessary.

In my opinion that is just boilerplate. Ideally you would not have to write it when implementing your own framework.

Do you agree?

**Comment by Starzu** [comment]
I don't think it's possible to remove this class. You have to define specific framework somewhere. Of course you can move copy-pasted parts (`rawTo*` methods) to a trait and use them in both `CirceServerREST` and `DefaultServerREST`.

**Comment by leonardehrenfried** [comment]
Ok, I followed your suggestion an implemented an ExposesREST for Circe: https://github.com/leonardehrenfried/udash-circe/blob/master/backend/src/main/scala/io/leonard/udash/CirceExposesREST.scala

I also extracted the utility methods into a trait:
https://github.com/leonardehrenfried/udash-circe/blob/master/shared/src/main/scala/io/leonard/udash/RESTConverters.scala

Would you be interested in having this trait in core so it can be reused?

**Comment by Starzu** [comment]
Sure. You can create PR with all these classes. I think we can publish them as part of Udash.

**Comment by leonardehrenfried** [comment]
I opened a PR with the utility trait.

However, I would like to keep the actual framework implementation in a separate repo because I don't want to tie the upgrade of the circe version to the release of udash.
