### ISSUE TITLE
Twitter Bootstrap support

### ISSUE THREAD

**Issue by Starzu** [UdashFramework/udash-core#20]
### Description

Prepare a Twitter Bootstrap wrapper integrated with the Udash features.

### TODO

* ~~check https://github.com/Karasiq/scalajs-bootstrap - this wrapper looks cool~~
* prepare the wrapper interface to be used with Udash Properties
* create a demo application in the Udash demos repo
* create the Twitter Bootstrap chapter in Dev's Guide

**Comment by ddworak** [comment]
Since we've decided to work on our own API for Bootstrap components, here is a simple, probably topologically sorted by "dependencies", **TODO** list:
- [ ] statics, attributes, styles
- [ ] Button (js) - prerequisite to almost everything
- [ ] Button groups
- [ ] Dropdown (js)
- [ ] Button dropdowns
- [ ] Badges
- [ ] FontAwesome + Glyphicons
- [ ] Page header
- [ ] Labels
- [ ] Modal (js)
- [ ] Wells
- [ ] Alerts
- [ ] Pagination
- [ ] Breadcrumbs
- [ ] Media object
- [ ] Collapse (js)
- [ ] Grid
- [ ] Thumbnails
- [ ] Navs
- [ ] Tab (js)
- [ ] Navbar
- [ ] Form
- [ ] Input groups
- [ ] List group
- [ ] Panels
- [ ] Jumbotron
- [ ] Progress bars
- [ ] Carousels (js)
- [ ] Responsive embed
- [ ] ScrollSpy (js)
- [ ] Tooltip (js)
- [ ] Popover (js)

Some of these are extremely trivial and won't end up as full-fledged components, a simple class might suffice.
