### ISSUE TITLE
Bootstrap 4 wrapper - broken show/hide events of date picker

### ISSUE THREAD

**Issue by Starzu** [UdashFramework/udash-core#228]
Waiting for a fix in the wrapped library.

**Comment by ddworak** [comment]
@bgrochal is this still an issue after https://github.com/UdashFramework/udash-core/pull/369?

**Comment by bgrochal** [comment]
Yes, it is. To clarify, this issue states that the `io.udash.bootstrap.datepicker.UdashDatePicker.DatePickerEvent.Show` event is not triggered when a date picker pops up because the `show.datetimepicker` event is not triggered by the [underlying library](https://tempusdominus.github.io/bootstrap-4/Events/#showdatetimepicker). Hence, the `show/hide on method call and emit events` unit test (placed under `io.udash.bootstrap.datepicker.UdashDatePickerTest`) is ignored.

Related: tempusdominus/bootstrap-4/issues/227.

**Comment by ddworak** [comment]
There seems to be a fairly straightforward workaround in https://github.com/tempusdominus/bootstrap-4/issues/227
