### ISSUE TITLE
Divergent Implicit Type Error for SeqProperty

### ISSUE THREAD

**Issue by KGoodale13** [UdashFramework/udash-core#271]
The following code puts the compiler into an infinite loop possibly because of a DivergentImplicitTypeError (Not completely sure it is infinite but I gave it a solid 20 minutes before I killed it):
```scala
private case class Chunk[T](
    var requested: Boolean = false,
    data: SeqProperty[T] = SeqProperty.blank
)
```

If I change `SeqProperty.blank` to `SeqProperty.blank[T]` it will throw an error saying it cannot find a implicit ProperyCreator[T] as it should.

**Comment by ddworak** [comment]
Thanks for the report!

The underlying issue is that you actually cannot do it like this in Scala, e.g. https://scalafiddle.io/sf/OVcJbld/0
```scala
case class Property[T]()
object Property {
  def create[T]: Property[T] = Property()
}

case class Dummy[T](
  p: Property[T] = Property.create  
)

val x = Dummy[Int]()
```
won't compile due to:
```
error: type mismatch;
 found   : ScalaFiddle.this.Property[scala.this.Nothing]
 required: ScalaFiddle.this.Property[scala.this.Int]
Note: scala.this.Nothing <: scala.this.Int, but class Property is invariant in type T.
You may wish to define T as +T instead. (SLS 4.5)
Error occurred in an application involving default arguments.
  val x = Dummy[Int]()
               ^
```
This unexpected behaviour is actually a part of the spec:
`The default argument expression e is type-checked with an expected type T' obtained by replacing all occurrences of the function's type parameters in T by the undefined type`
and in case of these implicits leads to huge mess in implicit resolution. More details: https://github.com/scala/scala-dev/issues/366#issuecomment-292457046 

Anyway, I've managed to reduce the number of `implicit def`s and macro usage to the point where detecting the issue is acceptably fast and covered by our test suite. https://github.com/UdashFramework/udash-core/pull/276
